image: rust:latest

stages:
  - pull_dependent_projects
  - build
  - test_unit

pull_vade:
  stage: pull_dependent_projects
  script:
    - cd ..
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN_VADE}@git.slock.it/equs/interop/vade/vade.git --branch develop

pull_vade_evan_bbs:
  stage: pull_dependent_projects
  script:
    - cd ..
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN_VADE_EVAN_BBS}@git.slock.it/equs/interop/vade/vade-evan-bbs.git --branch develop

pull_vade_evan_substrate:
  stage: pull_dependent_projects
  script:
    - cd ..
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN_EVAN_SUBSTRATE}@git.slock.it/equs/interop/vade/vade-evan-substrate.git  --branch develop

pull_vade_didcomm:
  stage: pull_dependent_projects
  script:
    - cd ..
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN_VADE_DIDCOMM}@git.slock.it/equs/interop/vade/vade-didcomm.git  --branch develop

build:
  stage: build
  script:
    - cargo build --release --verbose

test_unit:
  stage: test_unit
  script:
    - cargo test --release --verbose
