image: rust:latest

stages:
  - build
  - test_unit

build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y clang
    - cd ..
    - rm -rf vade vade-didcomm vade-evan-substrate vade-evan-cl vade-evan-bbs vade-universal-resolver
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/equs/interop/vade/vade-didcomm.git --branch develop
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/equs/interop/vade/vade-evan-substrate.git  --branch develop
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/equs/interop/vade/vade-evan-cl.git --branch develop
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/equs/interop/vade/vade-evan-bbs.git --branch develop
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/equs/interop/vade/vade.git --branch develop
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/equs/interop/vade/vade-universal-resolver.git --branch develop
    - cd vade-evan
    - cargo build --release --verbose
  artifacts:
    paths:
      - ./target
    expire_in: 1 hour

test_unit:
  stage: test_unit
  script:
    - apt-get update
    - apt-get install -y clang
    - cargo test --release --verbose -- -Z unstable-options --message-format json | cargo2junit > results.xml
    - 'export token=$("curl -X POST -H "Content-Type: application/json" -d "{ \"client_id\": \"${client_id}\", \"client_secret\": \"${client_secret}\" }" "https://xray.cloud.xpand-it.com/api/v2/authenticate"")'
    - echo $token
    - 'curl -X POST -H "Content-Type: text/xml" -H "Authorization: Bearer ${token}" -d "@results.xml" "https://xray.cloud.xpand-it.com/api/v2/import/execution/junit?projectKey=DID&testPlanKey=DID-74"'
