# see https://nbsoftsolutions.com/blog/azure-pipelines-for-rust-projects
strategy:
  matrix:
    windows-latest:
      imageName: 'windows-latest'
      rustup_toolchain: stable
    mac-latest:
      imageName: 'macOS-latest'
      rustup_toolchain: stable
    linux-latest:
      imageName: 'ubuntu-latest'
      rustup_toolchain: stable

pool:
  vmImage: $(imageName)

steps:
  - template: '_build/install-rust.yml'
  - script: echo "cargo build --all"
    displayName: Cargo build
  - script: echo "cargo test --all"
    displayName: Cargo test
  