# see https://nbsoftsolutions.com/blog/azure-pipelines-for-rust-projects
variables:
  build_command: cargo build --release
  test_command: cargo test --release

strategy:
  matrix:
    windows-latest-rust-nightly:
      imageName: 'windows-latest'
      rust_log: 'vade_evan::utils::substrate=trace'
      rustup_toolchain: nightly
    # mac-latest:
    #   imageName: 'macOS-latest'
    #   rustup_toolchain: stable
    # linux-latest:
    #   imageName: 'ubuntu-latest'
    #   rustup_toolchain: stable

pool:
  vmImage: $(imageName)

steps:
  - template: '_build/install-rust.yml'
  - script: $(build_command)
    displayName: Cargo build
  - script: $(test_command)
    displayName: Cargo test
  