[package]
name = "vade-tnt"
version = "0.0.1"
authors = ["Philip Kaiser <philip.kaiser@evan.team>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chrono = "0.4.11"
# we need to compile ursa manually because the latest published crate (0.3.2) does not support wasm yet
ursa = { path = "./../ursa/libursa", features=["portable_wasm"], default-features = false }
# ursa = "0.3.2"
rand = "0.7.3"
serde_json = { version = "1.0.53", features = ["preserve_order", "raw_value"] }
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2"
wee_alloc = { version = "0.4.5", optional = true }
sha3 = "0.8.2"
sha2 = "0.8.1"
libsecp256k1 = "0.3.5"
data-encoding = "2.2.0"
hex = "0.4.2"
log = "0.4.8"
regex = "1.3.7"
env_logger = "0.7.1"
async-trait = "0.1.31"
vade = { path = "../vade", version = "0.0.6" }
simple-error = "0.2.1"
uuid = { version = "0.8.1", features = ["serde", "v4", "wasm-bindgen"] }


[dev-dependencies]
wasm-bindgen-test = "0.3.12"
tokio = { version = "0.2.21", features = ["macros", "rt-threaded"] }
vade-evan = { path = "../vade-evan", version = "0.0.5" }

