[package]
name = "vade-evan"
version = "0.0.8"
authors = ["evan GmbH"]
edition = "2018"
license-file = "LICENSE.txt"
description = "zero-knowledge-proof VC and TnT DID handling for vade"
homepage = "https://github.com/evannetwork/vade-evan"
documentation = "https://docs.rs/crate/vade-evan"
repository = "https://github.com/evannetwork/vade-evan"
readme = "README.md"
keywords = ["did", "ssi", "vc", "zkp"]

[lib]
name = "vade_evan"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "vade_evan_cli"
path = "src/main.rs"
required-features = ["cli"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]

[features]
default = ["cli", "did", "portable", "vc-zkp"]

# add command line interface; not compatible with `wasm` feature
cli = [
    "clap",
    "did",
    "didcomm",
    "tokio",
    "vc-zkp",
]

# enables using DIDs, also required for some vc-zkp functions
did = [
    "vade-evan-substrate",
    "vade-universal-resolver",
]

# enables didcomm message features
didcomm = [
    "vade-didcomm",
]

# default ursa setup
portable = [
    "vade-evan-cl/portable",
]

# enables zero knowledge VC support
vc-zkp = [
    "vade-evan-bbs",
    "vade-evan-cl",
]

# build to run as wasm file; not compatible with `native` feature
wasm = [
    "vade-didcomm/wasm",
    "vade-evan-cl/wasm",
    "vade-evan-bbs/wasm",
]

[dependencies]
async-trait = "0.1.31"
cfg-if = "0.1"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.53", features = ["preserve_order", "raw_value"] }
vade = { path = "../vade", version = "0.1.0" }
###################################################################### feature specific dependencies
# feature "cl"
vade-evan-bbs = { path = "../vade-evan-bbs", version = "0.1.0", optional = true, default-features = false }
vade-evan-cl = { path = "../vade-evan-cl", version = "0.1.0", optional = true, default-features = false }
# feature "cli"
clap = { version = "2.33.1", optional = true }
tokio = { version = "=1.7.1", optional = true, features = ["rt-multi-thread", "macros"] }
# feature "did"
vade-evan-substrate = { path = "../vade-evan-substrate", version = "0.1.0", optional = true }
vade-universal-resolver = { path = "../vade-universal-resolver", version = "0.0.1", optional = true }
# feature "didcomm"
vade-didcomm = { path = "../vade-didcomm", version = "0.0.1", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
console_log = { version = "0.2", features = ["color"] }
log = "0.4.8"
serde_derive = "1.0.114"
wasm-bindgen = { version = "0.2",features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.5"

[dev-dependencies]
tokio = { version = "0.2.22", features = ["macros", "rt-threaded"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.12"
