[target.arm-unknown-linux-gnueabihf]
dockerfile = "./dockerfiles/Dockerfile.arm-unknown-linux-gnueabihf"

[target.aarch64-unknown-linux-gnu]
dockerfile = "./dockerfiles/Dockerfile.aarch64-unknown-linux-gnu"

[target.aarch64-linux-android]
dockerfile = "./dockerfiles/Dockerfile.aarch64-linux-android"

[target.i686-linux-android]
dockerfile = "./dockerfiles/Dockerfile.i686-linux-android"

[target.x86_64-linux-android]
dockerfile = "./dockerfiles/Dockerfile.x86_64-linux-android"

[target.armv7-linux-androideabi]
dockerfile = "./dockerfiles/Dockerfile.armv7-linux-androideabi"
