name: Build & Test - MacOS & Linux

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        target:
          [
            # linux builds
            x86_64-unknown-linux-gnu,
            aarch64-unknown-linux-gnu,
            arm-unknown-linux-gnueabihf,
            # macos builds
            x86_64-apple-darwin,
            aarch64-apple-darwin,
            # windows builds
            x86_64-pc-windows-msvc,
            x86_64-pc-windows-gnu,
            # android builds
            aarch64-linux-android,
            armv7-linux-androideabi,
            x86_64-linux-android,
            i686-linux-android,
            # ios builds
            aarch64-apple-ios,
            x86_64-apple-ios,
            aarch64-apple-ios-sim,
          ]
        toolchain: [stable]
        exclude:
          # Don't test linux/windows/android/ios targets on macos
          - os: macos-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: arm-unknown-linux-gnueabihf
          - os: macos-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-pc-windows-gnu
          - os: macos-latest
            target: aarch64-linux-android
          - os: macos-latest
            target: armv7-linux-androideabi
          - os: macos-latest
            target: x86_64-linux-android
          - os: macos-latest
            target: i686-linux-android
          - os: macos-latest
            target: aarch64-apple-ios
          - os: macos-latest
            target:  x86_64-apple-ios
          - os: macos-latest
            target: aarch64-apple-ios-sim
          # Don't test darwin/windows/ios targets on ubuntu
          - os: ubuntu-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
          - os: ubuntu-latest
            target: aarch64-apple-ios
          - os: ubuntu-latest
            target:  x86_64-apple-ios
          - os: ubuntu-latest
            target: aarch64-apple-ios-sim
          # Don't test darwin/linux/android/ios targets on windows
          - os: windows-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: aarch64-unknown-linux-gnu
          - os: windows-latest
            target: arm-unknown-linux-gnueabihf
          - os: windows-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: aarch64-apple-ios
          - os: windows-latest
            target:  x86_64-apple-ios
          - os: windows-latest
            target: aarch64-apple-ios-sim
          - os: windows-latest
            target: aarch64-linux-android
          - os: windows-latest
            target: armv7-linux-androideabi
          - os: windows-latest
            target: x86_64-linux-android
          - os: windows-latest
            target: i686-linux-android

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
          target: ${{ matrix.target }}
          override: true
      - run: rustup target add ${{ matrix.target }}
      - name: Install clang for ubuntu
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
               sudo apt install -y clang
          fi
        shell: bash
      - name: Install wasm-pack (with workaround for Linux)
        # see https://github.com/rustwasm/wasm-pack/issues/781#issuecomment-1242611389
        # and https://github.com/rustwasm/wasm-pack/issues/823#issuecomment-1242611318
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: cargo install --git https://github.com/frewsxcv/wasm-pack.git --branch patch-2
      - name: Install wasm-pack (with official script)
        if: ${{ matrix.os != 'ubuntu-latest'}}
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: wasm-build
        run: wasm-pack build --release --target nodejs -- --no-default-features --features bundle-default,target-wasm --target-dir=target/
      - name: install cross
        run: cargo install -f cross
      - name: bundle-sdk native build
        if: ${{ matrix.target != 'aarch64-linux-android' && matrix.target != 'armv7-linux-androideabi' && matrix.target != 'x86_64-linux-android' && matrix.target != 'i686-linux-android'}}
        run: cargo build --release --no-default-features --features bundle-sdk,target-c-lib --target-dir=target/ --target=${{ matrix.target }}
      - name: bundle-sdk cross build
        if: ${{ matrix.target == 'aarch64-linux-android' || matrix.target == 'armv7-linux-androideabi' || matrix.target == 'x86_64-linux-android' || matrix.target == 'i686-linux-android'}}
        run: cross build --release --no-default-features --features bundle-sdk,target-c-lib --target-dir target/ --target ${{ matrix.target }}
      - name: Run tests
        run: cargo test --verbose
      - uses: haya14busa/action-cond@v1
        id: files
        with:
          cond: ${{ matrix.os == 'windows-latest' }}
          if_true: "vade_evan_cli.exe"
          if_false: "vade_evan_cli"
      - name: Compress files
        uses: vimtor/action-zip@v1
        with:
          files: target/${{ matrix.target }}/release/${{ steps.files.outputs.value }} target/wasm32-unknown-unknown
          dest: target/${{ matrix.target }}.zip
